from odoo import api, fields, models, _


class TetrapayPayments(models.Model):
    _name = 'tetrapay.payments'

    ACQBIN = fields.Char('ACQBIN', default=None)
    AuthCode = fields.Char('AuthCode', default=False)
    BillToName = fields.Char('BillToName', default=None)
    CARDBRAND = fields.Char('CARDBRAND', default=None)
    CARDISSUER = fields.Char('CARDISSUER', default=None)
    TRXDATE = fields.Char('TRXDATE', default=None)
    ExpDate_Month = fields.Char('ExpDate_Month', default=None)
    ExpDate_Year = fields.Char('ExpDate_Year', default=None)
    ErrMsg = fields.Char('ErrMsg', default=None)
    HASH = fields.Char('HASH', default=None)
    HostRefNum = fields.Char('HostRefNum', default=None)
    MaskedPan = fields.Char('MaskedPan', default=None)
    PAResSyntaxOK = fields.Char('PAResSyntaxOK', default=None)
    PAResVerified = fields.Char('PAResVerified', default=None)
    ProcReturnCode = fields.Char('ProcReturnCode', default=None)
    Response = fields.Char('Response', default=None)
    ReturnOid = fields.Char('ReturnOid', default=None)
    SettleId = fields.Char('SettleId', default=None)
    RReqExtensions = fields.Char('RReqExtensions', default=None)
    acsOperatorID = fields.Char('acsOperatorID', default=None)
    acsReferenceNumber = fields.Char('acsReferenceNumber', default=None)
    acsTransID = fields.Char('acsTransID', default=None)
    authTimestamp = fields.Char('authTimestamp', default=None)
    authenticationType = fields.Char('authenticationType', default=None)
    dsTransID = fields.Char('dsTransID', default=None)
    threeDSServerTransID = fields.Char('threeDSServerTransID', default=None)
    transStatus = fields.Char('Ship To Name', default=None)
    TRANID = fields.Char('TRANID', default=None)
    TransId = fields.Char('TransId', default=None)
    acqStan = fields.Char('acqStan', default=None)
    amount = fields.Char('amount', default=None)
    callbackCall = fields.Char('callbackCall', default=None)
    cavv = fields.Char('cavv', default=None)
    clientIp = fields.Char('clientIp', default=None)
    clientid = fields.Char('clientid', default=None)
    currency = fields.Char('currency', default=None)
    digest = fields.Char('digest', default=None)
    dsId = fields.Char('dsId', default=None)
    eci = fields.Char('eci', default=None)
    email = fields.Char('email', default=None)
    encoding = fields.Char('encoding', default=None)
    failUrl = fields.Char('failUrl', default=None)
    fismi = fields.Char('fismi', default=None)
    hashAlgorithm = fields.Char('hashAlgorithm', default=None)
    maskedCreditCard = fields.Char('maskedCreditCard', default=None)
    md = fields.Char('md', default=None)
    mdErrorMsg = fields.Char('mdErrorMsg', default=None)
    mdStatus = fields.Char('mdStatus', default=None)
    merchantID = fields.Char('merchantID', default=None)
    merchantName = fields.Char('merchantName', default=None)
    oid = fields.Char('oid', default=None)
    okUrl = fields.Char('okUrl', default=None)
    paresTxStatus = fields.Char('paresTxStatus', default=None)
    dsId = fields.Char('dsId', default=None)
    protocol = fields.Char('protocol', default=None)
    querypointhash = fields.Char('querypointhash', default=None)
    refreshtime = fields.Char('refreshtime', default=None)
    rnd = fields.Char('rnd', default=None)
    sID = fields.Char('sID', default=None)
    signature = fields.Char('signature', default=None)
    storetype = fields.Char('storetype', default=None)
    trantype = fields.Char('trantype', default=None)
    cavvAlgorthm = fields.Char('CAVV Algorithm', default=None)
    userselectedinstalment = fields.Char('userselectedinstalment', default=None)
    veresEnrolledStatus = fields.Char('veresEnrolledStatus', default=None)
    version = fields.Char('version', default=None)
    x = fields.Char('x', default=None)
    xid = fields.Char('xid', default=None)
    y = fields.Char('y', default=None)
